// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommentItem {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub post_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub author_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub author_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub body: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "6")]
    pub parent_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, tag = "7")]
    pub like_count: u64,
    #[prost(string, tag = "8")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(enumeration = "CommentStatus", tag = "9")]
    pub status: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateCommentResult {
    #[prost(message, optional, tag = "1")]
    pub comment: ::core::option::Option<CommentItem>,
    #[prost(string, optional, tag = "2")]
    pub parent_author_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListRequest {
    #[prost(string, tag = "1")]
    pub post_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "3")]
    pub limit: ::core::option::Option<u32>,
    #[prost(string, repeated, tag = "4")]
    pub excluded_author_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommentPage {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<CommentItem>,
    #[prost(string, optional, tag = "2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub post_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub idempotency_key: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub body: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "5")]
    pub parent_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "6")]
    pub excluded_author_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub post_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub comment_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteResponse {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListModerationRequest {
    #[prost(string, optional, tag = "1")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "2")]
    pub limit: ::core::option::Option<u32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModerationCommentPage {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<CommentItem>,
    #[prost(string, optional, tag = "2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReviewCommentRequest {
    #[prost(string, tag = "1")]
    pub reviewer_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub comment_id: ::prost::alloc::string::String,
    #[prost(enumeration = "CommentModerationDecision", tag = "3")]
    pub decision: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReviewCommentResult {
    #[prost(message, optional, tag = "1")]
    pub comment: ::core::option::Option<CommentItem>,
    #[prost(string, optional, tag = "2")]
    pub parent_author_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateCommentReportRequest {
    #[prost(string, tag = "1")]
    pub reporter_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub post_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub comment_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub idempotency_key: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "CommentReportReason", tag = "5")]
    pub reason: i32,
    #[prost(string, tag = "6")]
    pub details: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "7")]
    pub excluded_author_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommentReport {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reporter_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub reported_comment: ::core::option::Option<CommentItem>,
    #[prost(enumeration = "CommentReportReason", tag = "4")]
    pub reason: i32,
    #[prost(string, tag = "5")]
    pub details: ::prost::alloc::string::String,
    #[prost(enumeration = "CommentReportStatus", tag = "6")]
    pub status: i32,
    #[prost(string, optional, tag = "7")]
    pub reviewer_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "8")]
    pub resolution: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "CommentReportAction", tag = "9")]
    pub action: i32,
    #[prost(string, tag = "10")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub updated_at: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListCommentReportsRequest {
    #[prost(enumeration = "CommentReportStatus", optional, tag = "1")]
    pub status: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "3")]
    pub limit: ::core::option::Option<u32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommentReportPage {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<CommentReport>,
    #[prost(string, optional, tag = "2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReviewCommentReportRequest {
    #[prost(string, tag = "1")]
    pub reviewer_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub report_id: ::prost::alloc::string::String,
    #[prost(enumeration = "CommentReportStatus", tag = "3")]
    pub status: i32,
    #[prost(string, tag = "4")]
    pub resolution: ::prost::alloc::string::String,
    #[prost(enumeration = "CommentReportAction", tag = "5")]
    pub action: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateCommentAppealRequest {
    #[prost(string, tag = "1")]
    pub author_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub comment_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub idempotency_key: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub details: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommentAppeal {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub author_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub appealed_comment: ::core::option::Option<CommentItem>,
    #[prost(string, tag = "4")]
    pub details: ::prost::alloc::string::String,
    #[prost(enumeration = "CommentAppealStatus", tag = "5")]
    pub status: i32,
    #[prost(string, optional, tag = "6")]
    pub reviewer_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub resolution: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "CommentAppealAction", tag = "8")]
    pub action: i32,
    #[prost(string, tag = "9")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub updated_at: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListCommentAppealsRequest {
    #[prost(string, optional, tag = "1")]
    pub author_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "CommentAppealStatus", optional, tag = "2")]
    pub status: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "3")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "4")]
    pub limit: ::core::option::Option<u32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommentAppealPage {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<CommentAppeal>,
    #[prost(string, optional, tag = "2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReviewCommentAppealRequest {
    #[prost(string, tag = "1")]
    pub reviewer_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub appeal_id: ::prost::alloc::string::String,
    #[prost(enumeration = "CommentAppealStatus", tag = "3")]
    pub status: i32,
    #[prost(string, tag = "4")]
    pub resolution: ::prost::alloc::string::String,
    #[prost(enumeration = "CommentAppealAction", tag = "5")]
    pub action: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CommentStatus {
    Reviewing = 0,
    Published = 1,
    Restricted = 2,
    Deleted = 3,
}
impl CommentStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Reviewing => "COMMENT_STATUS_REVIEWING",
            Self::Published => "COMMENT_STATUS_PUBLISHED",
            Self::Restricted => "COMMENT_STATUS_RESTRICTED",
            Self::Deleted => "COMMENT_STATUS_DELETED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMMENT_STATUS_REVIEWING" => Some(Self::Reviewing),
            "COMMENT_STATUS_PUBLISHED" => Some(Self::Published),
            "COMMENT_STATUS_RESTRICTED" => Some(Self::Restricted),
            "COMMENT_STATUS_DELETED" => Some(Self::Deleted),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CommentModerationDecision {
    Unspecified = 0,
    Approve = 1,
    Restrict = 2,
}
impl CommentModerationDecision {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "COMMENT_MODERATION_DECISION_UNSPECIFIED",
            Self::Approve => "COMMENT_MODERATION_DECISION_APPROVE",
            Self::Restrict => "COMMENT_MODERATION_DECISION_RESTRICT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMMENT_MODERATION_DECISION_UNSPECIFIED" => Some(Self::Unspecified),
            "COMMENT_MODERATION_DECISION_APPROVE" => Some(Self::Approve),
            "COMMENT_MODERATION_DECISION_RESTRICT" => Some(Self::Restrict),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CommentReportReason {
    Unspecified = 0,
    Spam = 1,
    Harassment = 2,
    Unsafe = 3,
    Fraud = 4,
    Privacy = 5,
    Other = 6,
}
impl CommentReportReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "COMMENT_REPORT_REASON_UNSPECIFIED",
            Self::Spam => "COMMENT_REPORT_REASON_SPAM",
            Self::Harassment => "COMMENT_REPORT_REASON_HARASSMENT",
            Self::Unsafe => "COMMENT_REPORT_REASON_UNSAFE",
            Self::Fraud => "COMMENT_REPORT_REASON_FRAUD",
            Self::Privacy => "COMMENT_REPORT_REASON_PRIVACY",
            Self::Other => "COMMENT_REPORT_REASON_OTHER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMMENT_REPORT_REASON_UNSPECIFIED" => Some(Self::Unspecified),
            "COMMENT_REPORT_REASON_SPAM" => Some(Self::Spam),
            "COMMENT_REPORT_REASON_HARASSMENT" => Some(Self::Harassment),
            "COMMENT_REPORT_REASON_UNSAFE" => Some(Self::Unsafe),
            "COMMENT_REPORT_REASON_FRAUD" => Some(Self::Fraud),
            "COMMENT_REPORT_REASON_PRIVACY" => Some(Self::Privacy),
            "COMMENT_REPORT_REASON_OTHER" => Some(Self::Other),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CommentReportStatus {
    Pending = 0,
    Reviewing = 1,
    Resolved = 2,
    Rejected = 3,
}
impl CommentReportStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Pending => "COMMENT_REPORT_STATUS_PENDING",
            Self::Reviewing => "COMMENT_REPORT_STATUS_REVIEWING",
            Self::Resolved => "COMMENT_REPORT_STATUS_RESOLVED",
            Self::Rejected => "COMMENT_REPORT_STATUS_REJECTED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMMENT_REPORT_STATUS_PENDING" => Some(Self::Pending),
            "COMMENT_REPORT_STATUS_REVIEWING" => Some(Self::Reviewing),
            "COMMENT_REPORT_STATUS_RESOLVED" => Some(Self::Resolved),
            "COMMENT_REPORT_STATUS_REJECTED" => Some(Self::Rejected),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CommentReportAction {
    NoAction = 0,
    RestrictComment = 1,
}
impl CommentReportAction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NoAction => "COMMENT_REPORT_ACTION_NO_ACTION",
            Self::RestrictComment => "COMMENT_REPORT_ACTION_RESTRICT_COMMENT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMMENT_REPORT_ACTION_NO_ACTION" => Some(Self::NoAction),
            "COMMENT_REPORT_ACTION_RESTRICT_COMMENT" => Some(Self::RestrictComment),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CommentAppealStatus {
    Pending = 0,
    Reviewing = 1,
    Resolved = 2,
    Rejected = 3,
}
impl CommentAppealStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Pending => "COMMENT_APPEAL_STATUS_PENDING",
            Self::Reviewing => "COMMENT_APPEAL_STATUS_REVIEWING",
            Self::Resolved => "COMMENT_APPEAL_STATUS_RESOLVED",
            Self::Rejected => "COMMENT_APPEAL_STATUS_REJECTED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMMENT_APPEAL_STATUS_PENDING" => Some(Self::Pending),
            "COMMENT_APPEAL_STATUS_REVIEWING" => Some(Self::Reviewing),
            "COMMENT_APPEAL_STATUS_RESOLVED" => Some(Self::Resolved),
            "COMMENT_APPEAL_STATUS_REJECTED" => Some(Self::Rejected),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CommentAppealAction {
    NoAction = 0,
    RestoreComment = 1,
}
impl CommentAppealAction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NoAction => "COMMENT_APPEAL_ACTION_NO_ACTION",
            Self::RestoreComment => "COMMENT_APPEAL_ACTION_RESTORE_COMMENT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMMENT_APPEAL_ACTION_NO_ACTION" => Some(Self::NoAction),
            "COMMENT_APPEAL_ACTION_RESTORE_COMMENT" => Some(Self::RestoreComment),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod comment_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct CommentClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl CommentClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CommentClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CommentClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            CommentClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn list(
            &mut self,
            request: impl tonic::IntoRequest<super::ListRequest>,
        ) -> std::result::Result<tonic::Response<super::CommentPage>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.comment.Comment/List",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("bookway.comment.Comment", "List"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn create(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateCommentResult>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.comment.Comment/Create",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("bookway.comment.Comment", "Create"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteRequest>,
        ) -> std::result::Result<tonic::Response<super::DeleteResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.comment.Comment/Delete",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("bookway.comment.Comment", "Delete"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_moderation(
            &mut self,
            request: impl tonic::IntoRequest<super::ListModerationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ModerationCommentPage>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.comment.Comment/ListModeration",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("bookway.comment.Comment", "ListModeration"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn review(
            &mut self,
            request: impl tonic::IntoRequest<super::ReviewCommentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReviewCommentResult>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.comment.Comment/Review",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("bookway.comment.Comment", "Review"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn report(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateCommentReportRequest>,
        ) -> std::result::Result<tonic::Response<super::CommentReport>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.comment.Comment/Report",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("bookway.comment.Comment", "Report"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_reports(
            &mut self,
            request: impl tonic::IntoRequest<super::ListCommentReportsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CommentReportPage>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.comment.Comment/ListReports",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("bookway.comment.Comment", "ListReports"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn review_report(
            &mut self,
            request: impl tonic::IntoRequest<super::ReviewCommentReportRequest>,
        ) -> std::result::Result<tonic::Response<super::CommentReport>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.comment.Comment/ReviewReport",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("bookway.comment.Comment", "ReviewReport"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn appeal(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateCommentAppealRequest>,
        ) -> std::result::Result<tonic::Response<super::CommentAppeal>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.comment.Comment/Appeal",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("bookway.comment.Comment", "Appeal"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_appeals(
            &mut self,
            request: impl tonic::IntoRequest<super::ListCommentAppealsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CommentAppealPage>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.comment.Comment/ListAppeals",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("bookway.comment.Comment", "ListAppeals"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn review_appeal(
            &mut self,
            request: impl tonic::IntoRequest<super::ReviewCommentAppealRequest>,
        ) -> std::result::Result<tonic::Response<super::CommentAppeal>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.comment.Comment/ReviewAppeal",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("bookway.comment.Comment", "ReviewAppeal"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod comment_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with CommentServer.
    #[async_trait]
    pub trait Comment: std::marker::Send + std::marker::Sync + 'static {
        async fn list(
            &self,
            request: tonic::Request<super::ListRequest>,
        ) -> std::result::Result<tonic::Response<super::CommentPage>, tonic::Status>;
        async fn create(
            &self,
            request: tonic::Request<super::CreateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateCommentResult>,
            tonic::Status,
        >;
        async fn delete(
            &self,
            request: tonic::Request<super::DeleteRequest>,
        ) -> std::result::Result<tonic::Response<super::DeleteResponse>, tonic::Status>;
        async fn list_moderation(
            &self,
            request: tonic::Request<super::ListModerationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ModerationCommentPage>,
            tonic::Status,
        >;
        async fn review(
            &self,
            request: tonic::Request<super::ReviewCommentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReviewCommentResult>,
            tonic::Status,
        >;
        async fn report(
            &self,
            request: tonic::Request<super::CreateCommentReportRequest>,
        ) -> std::result::Result<tonic::Response<super::CommentReport>, tonic::Status>;
        async fn list_reports(
            &self,
            request: tonic::Request<super::ListCommentReportsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CommentReportPage>,
            tonic::Status,
        >;
        async fn review_report(
            &self,
            request: tonic::Request<super::ReviewCommentReportRequest>,
        ) -> std::result::Result<tonic::Response<super::CommentReport>, tonic::Status>;
        async fn appeal(
            &self,
            request: tonic::Request<super::CreateCommentAppealRequest>,
        ) -> std::result::Result<tonic::Response<super::CommentAppeal>, tonic::Status>;
        async fn list_appeals(
            &self,
            request: tonic::Request<super::ListCommentAppealsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CommentAppealPage>,
            tonic::Status,
        >;
        async fn review_appeal(
            &self,
            request: tonic::Request<super::ReviewCommentAppealRequest>,
        ) -> std::result::Result<tonic::Response<super::CommentAppeal>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct CommentServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> CommentServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for CommentServer<T>
    where
        T: Comment,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/bookway.comment.Comment/List" => {
                    #[allow(non_camel_case_types)]
                    struct ListSvc<T: Comment>(pub Arc<T>);
                    impl<T: Comment> tonic::server::UnaryService<super::ListRequest>
                    for ListSvc<T> {
                        type Response = super::CommentPage;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Comment>::list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.comment.Comment/Create" => {
                    #[allow(non_camel_case_types)]
                    struct CreateSvc<T: Comment>(pub Arc<T>);
                    impl<T: Comment> tonic::server::UnaryService<super::CreateRequest>
                    for CreateSvc<T> {
                        type Response = super::CreateCommentResult;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Comment>::create(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.comment.Comment/Delete" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteSvc<T: Comment>(pub Arc<T>);
                    impl<T: Comment> tonic::server::UnaryService<super::DeleteRequest>
                    for DeleteSvc<T> {
                        type Response = super::DeleteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Comment>::delete(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.comment.Comment/ListModeration" => {
                    #[allow(non_camel_case_types)]
                    struct ListModerationSvc<T: Comment>(pub Arc<T>);
                    impl<
                        T: Comment,
                    > tonic::server::UnaryService<super::ListModerationRequest>
                    for ListModerationSvc<T> {
                        type Response = super::ModerationCommentPage;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListModerationRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Comment>::list_moderation(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListModerationSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.comment.Comment/Review" => {
                    #[allow(non_camel_case_types)]
                    struct ReviewSvc<T: Comment>(pub Arc<T>);
                    impl<
                        T: Comment,
                    > tonic::server::UnaryService<super::ReviewCommentRequest>
                    for ReviewSvc<T> {
                        type Response = super::ReviewCommentResult;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReviewCommentRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Comment>::review(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReviewSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.comment.Comment/Report" => {
                    #[allow(non_camel_case_types)]
                    struct ReportSvc<T: Comment>(pub Arc<T>);
                    impl<
                        T: Comment,
                    > tonic::server::UnaryService<super::CreateCommentReportRequest>
                    for ReportSvc<T> {
                        type Response = super::CommentReport;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateCommentReportRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Comment>::report(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReportSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.comment.Comment/ListReports" => {
                    #[allow(non_camel_case_types)]
                    struct ListReportsSvc<T: Comment>(pub Arc<T>);
                    impl<
                        T: Comment,
                    > tonic::server::UnaryService<super::ListCommentReportsRequest>
                    for ListReportsSvc<T> {
                        type Response = super::CommentReportPage;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListCommentReportsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Comment>::list_reports(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListReportsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.comment.Comment/ReviewReport" => {
                    #[allow(non_camel_case_types)]
                    struct ReviewReportSvc<T: Comment>(pub Arc<T>);
                    impl<
                        T: Comment,
                    > tonic::server::UnaryService<super::ReviewCommentReportRequest>
                    for ReviewReportSvc<T> {
                        type Response = super::CommentReport;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReviewCommentReportRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Comment>::review_report(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReviewReportSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.comment.Comment/Appeal" => {
                    #[allow(non_camel_case_types)]
                    struct AppealSvc<T: Comment>(pub Arc<T>);
                    impl<
                        T: Comment,
                    > tonic::server::UnaryService<super::CreateCommentAppealRequest>
                    for AppealSvc<T> {
                        type Response = super::CommentAppeal;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateCommentAppealRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Comment>::appeal(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AppealSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.comment.Comment/ListAppeals" => {
                    #[allow(non_camel_case_types)]
                    struct ListAppealsSvc<T: Comment>(pub Arc<T>);
                    impl<
                        T: Comment,
                    > tonic::server::UnaryService<super::ListCommentAppealsRequest>
                    for ListAppealsSvc<T> {
                        type Response = super::CommentAppealPage;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListCommentAppealsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Comment>::list_appeals(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListAppealsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.comment.Comment/ReviewAppeal" => {
                    #[allow(non_camel_case_types)]
                    struct ReviewAppealSvc<T: Comment>(pub Arc<T>);
                    impl<
                        T: Comment,
                    > tonic::server::UnaryService<super::ReviewCommentAppealRequest>
                    for ReviewAppealSvc<T> {
                        type Response = super::CommentAppeal;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReviewCommentAppealRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Comment>::review_appeal(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReviewAppealSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for CommentServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "bookway.comment.Comment";
    impl<T> tonic::server::NamedService for CommentServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
