[package]
name = "bookway-recommend-main"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bookway-recommend-main-api.workspace = true
async-trait.workspace = true
axum.workspace = true
bookway-api.workspace = true
bookway-cache.workspace = true
bookway-commercial-mix.workspace = true
bookway-data.workspace = true
bookway-runtime.workspace = true
bookway-recommend-recall-api.workspace = true
bookway-recommend-rank-api.workspace = true
bookway-ad-main-api.workspace = true
bookway-bbs-api.workspace = true
bookway-bbs-link-api.workspace = true
bookway-interaction-status-api.workspace = true
bookway-feature-main-api.workspace = true
futures.workspace = true
redis.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
uuid.workspace = true
tonic.workspace = true
tonic-health.workspace = true
prost.workspace = true

[lints]
workspace = true
