name: bookway-recommend-main
owner: recommendation
kind: grpc-service
port: 8083
healthcheck: grpc
dependencies:
  - bookway-bbs
  - bookway-commonlikestatus
  - bookway-recommend-recall
  - bookway-recommend-rank
  - bookway-feature-main
contracts:
  - src/api/pb/server.proto
