[package]
name = "bookway-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bookway-gateway-api.workspace = true
async-trait.workspace = true
axum.workspace = true
bookway-api.workspace = true
bookway-account-api.workspace = true
bookway-ad-center-api.workspace = true
bookway-ad-main-api.workspace = true
bookway-bbs-api.workspace = true
bookway-bbs-creator-api.workspace = true
bookway-bbs-feed-api.workspace = true
bookway-bbs-link-api.workspace = true
bookway-bbs-message-api.workspace = true
bookway-comment-api.workspace = true
bookway-interaction-status-api.workspace = true
bookway-content-audit-api.workspace = true
bookway-data.workspace = true
bookway-feedback-api.workspace = true
bookway-growth-api.workspace = true
bookway-knowledge-catalog-api.workspace = true
bookway-media-api.workspace = true
bookway-recommend-main-api.workspace = true
bookway-mall-api.workspace = true
bookway-mall-order-api.workspace = true
bookway-search-main-api.workspace = true
bookway-bbs-search-api.workspace = true
bookway-user-event-api.workspace = true
bookway-runtime.workspace = true
reqwest.workspace = true
tonic.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
time.workspace = true
tower-http.workspace = true
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true
