[package]
name = "bookway-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
bookway-api.workspace = true
bookway-bbs.workspace = true
bookway-bbs-feed.workspace = true
bookway-bbs-link.workspace = true
bookway-comment.workspace = true
bookway-commonlikestatus.workspace = true
bookway-content-audit.workspace = true
bookway-growth.workspace = true
bookway-media.workspace = true
bookway-search-main.workspace = true
bookway-user-event.workspace = true
bookway-runtime.workspace = true
reqwest.workspace = true
tonic.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true

[lints]
workspace = true
