[package]
name = "bookway-ad-recall-api"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bookway-api.workspace = true
serde.workspace = true
prost.workspace = true
tonic.workspace = true
bookway-ad-center-api.workspace = true

[build-dependencies]
tonic-build.workspace = true

[lints]
workspace = true
