[package]
name = "bookway-mall-order-expirer"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bookway-api.workspace = true
bookway-mall-order-api.workspace = true
bookway-runtime.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true

[lints]
workspace = true
