[package]
name = "bookway-mall"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bookway-mall-api.workspace = true
bookway-bbs-link-api.workspace = true
bookway-knowledge-catalog-api.workspace = true
async-trait.workspace = true
bookway-api.workspace = true
bookway-cache.workspace = true
bookway-data.workspace = true
bookway-runtime.workspace = true
prost.workspace = true
redis.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-health.workspace = true
tracing.workspace = true
uuid.workspace = true


[lints]
workspace = true
