[package]
name = "bookway-ad-main"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bookway-ad-main-api.workspace = true
bookway-ad-center-api.workspace = true
bookway-ad-rank-api.workspace = true
bookway-ad-recall-api.workspace = true
bookway-api.workspace = true
bookway-runtime.workspace = true
prost.workspace = true
thiserror.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-health.workspace = true
uuid.workspace = true


[lints]
workspace = true
