[package]
name = "bookway-feature-main"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bookway-feature-main-api.workspace = true
axum.workspace = true
bookway-api.workspace = true
bookway-data.workspace = true
bookway-runtime.workspace = true
redis.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
tonic.workspace = true
tonic-health.workspace = true
tower.workspace = true
prost.workspace = true

[lints]
workspace = true
