import { FormEvent, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import '../styles.css';

type View = 'overview' | 'products' | 'orders' | 'inventory' | 'offers' | 'finance';
type Product = { name: string; sku: string; price: string; stock: number; sales: number; status: '销售中' | '待发布'; image: string };
type Order = { id: string; date: string; product: string; recipient: string; city: string; amount: string; status: '待发货' | '运输中' | '已完成' };

const productImages = [
  'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=96&q=80',
  'https://images.unsplash.com/photo-1521334884684-d80222895322?auto=format&fit=crop&w=96&q=80',
  'https://images.unsplash.com/photo-1544967082-d9d25d867d66?auto=format&fit=crop&w=96&q=80',
  'https://images.unsplash.com/photo-1517825738774-7de9363ef735?auto=format&fit=crop&w=96&q=80',
];
const initialProducts: Product[] = [
  { name: '轻量徒步背包 20L', sku: 'SKU-TR20-G · 岩灰色', price: '¥329.00', stock: 8, sales: 246, status: '销售中', image: productImages[0] },
  { name: '快干徒步袜 3 双装', sku: 'SKU-SK03-D · 深灰色', price: '¥78.00', stock: 12, sales: 418, status: '销售中', image: productImages[1] },
  { name: '折叠露营灯', sku: 'SKU-LG01-W · 暖白光', price: '¥89.00', stock: 6, sales: 167, status: '销售中', image: productImages[2] },
  { name: '山野保温杯', sku: 'SKU-BT01-G · 森林绿', price: '¥119.00', stock: 64, sales: 0, status: '待发布', image: productImages[3] },
];
const initialOrders: Order[] = [
  { id: 'BW202608180128', date: '今天 10:42', product: '轻量徒步背包 20L × 1', recipient: '张晓', city: '北京朝阳', amount: '¥329.00', status: '待发货' },
  { id: 'BW202608180125', date: '今天 10:18', product: '快干徒步袜 3 双装 × 2', recipient: '陈舟', city: '上海徐汇', amount: '¥156.00', status: '待发货' },
  { id: 'BW202608170915', date: '昨天 17:18', product: '折叠露营灯 × 1', recipient: '吴悦', city: '杭州西湖', amount: '¥89.00', status: '运输中' },
  { id: 'BW202608160627', date: '8 月 16 日', product: '山野保温杯 × 1', recipient: '陆青', city: '南京鼓楼', amount: '¥119.00', status: '已完成' },
];
const nav: { view: View; label: string; icon: string }[] = [
  { view: 'overview', label: '经营总览', icon: '▦' }, { view: 'products', label: '商品管理', icon: '◇' }, { view: 'orders', label: '订单中心', icon: '▤' }, { view: 'inventory', label: '库存管理', icon: '▤' }, { view: 'offers', label: '路线商品', icon: '↗' }, { view: 'finance', label: '财务结算', icon: '¥' },
];
const titles: Record<View, string> = { overview: '经营总览', products: '商品管理', orders: '订单中心', inventory: '库存管理', offers: '路线商品', finance: '财务结算' };

function App() {
  const [view, setView] = useState<View>((location.hash.slice(1) as View) || 'overview');
  const [menuOpen, setMenuOpen] = useState(false);
  const [products, setProducts] = useState(initialProducts);
  const [orders, setOrders] = useState(initialOrders);
  const [productSearch, setProductSearch] = useState('');
  const [productStatus, setProductStatus] = useState('all');
  const [orderFilter, setOrderFilter] = useState('all');
  const [toast, setToast] = useState('');
  const [showProductForm, setShowProductForm] = useState(false);
  const [showStockForm, setShowStockForm] = useState(false);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2600); };
  const navigate = (next: View) => { setView(next); setMenuOpen(false); history.replaceState(null, '', `#${next}`); };
  const filteredProducts = useMemo(() => products.filter((product) => (productStatus === 'all' || (productStatus === 'selling') === (product.status === '销售中')) && `${product.name} ${product.sku}`.toLowerCase().includes(productSearch.toLowerCase())), [products, productSearch, productStatus]);
  const filteredOrders = orderFilter === 'all' ? orders : orders.filter((order) => order.status === orderFilter);
  const ship = (id: string) => { setOrders((current) => current.map((order) => order.id === id ? { ...order, status: '运输中' } : order)); notify('已进入发货流程，请在物流系统填写单号。'); };
  const createProduct = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const name = String(data.get('name') || '').trim(); const price = Number(data.get('price')); const stock = Number(data.get('stock')); setProducts((current) => [{ name, sku: `SKU-${Date.now().toString().slice(-5)} · 默认规格`, price: `¥${price.toFixed(2)}`, stock, sales: 0, status: '待发布', image: productImages[3] }, ...current]); setShowProductForm(false); notify(`“${name}”已创建，当前为待发布状态。`); };
  const adjustStock = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const quantity = Number(data.get('quantity')); setProducts((current) => current.map((product, index) => index === 0 ? { ...product, stock: product.stock + quantity } : product)); setShowStockForm(false); notify(`已增加 ${quantity} 件可售库存。`); };
  return <div className="app-shell">
    <aside className={`sidebar ${menuOpen ? 'open' : ''}`}><a className="brand" href="#overview" onClick={() => navigate('overview')}><span className="brand-mark">B</span><span>BOOKWAY</span></a><div className="store-switcher"><span className="store-avatar">青</span><span><strong>青云户外</strong><small>旗舰店</small></span><button className="icon-button" title="切换店铺">⌄</button></div><nav>{nav.map((item) => <a className={`nav-item ${view === item.view ? 'active' : ''}`} href={`#${item.view}`} key={item.view} onClick={(event) => { event.preventDefault(); navigate(item.view); }}><span>{item.icon}</span>{item.label}{item.view === 'orders' && <b>{orders.filter((order) => order.status === '待发货').length}</b>}</a>)}</nav><div className="sidebar-footer"><a className="nav-item" href="#"><span>⚙</span>店铺设置</a><div className="help"><strong>需要帮助？</strong><span>商家支持 · 09:00-21:00</span></div></div></aside>
    <main><header className="topbar"><button className="mobile-menu icon-button" title="打开导航" onClick={() => setMenuOpen(!menuOpen)}>☰</button><div className="breadcrumb"><span>商家中心</span><i>/</i><strong>{titles[view]}</strong></div><div className="top-actions"><button className="icon-button notification" title="消息通知">♢<em>3</em></button><button className="account"><span className="avatar">林</span><span>林青</span><small>⌄</small></button></div></header>
      {view === 'overview' && <Overview products={products} orders={orders} onNavigate={navigate} onNewProduct={() => setShowProductForm(true)} onShip={ship} onStock={() => setShowStockForm(true)} notify={notify} />}
      {view === 'products' && <Products products={filteredProducts} search={productSearch} status={productStatus} onSearch={setProductSearch} onStatus={setProductStatus} onNew={() => setShowProductForm(true)} />}
      {view === 'orders' && <Orders orders={filteredOrders} filter={orderFilter} onFilter={setOrderFilter} onShip={ship} />}
      {view === 'inventory' && <Inventory products={products} onAdjust={() => setShowStockForm(true)} />}
      {view === 'offers' && <Placeholder eyebrow="场景化商城" title="路线商品" description="将销售中的 SKU 关联到公开路线的行动节点，用户只会在相应场景中看到商品。" icon="↗" action="管理关联" />}
      {view === 'finance' && <Placeholder eyebrow="账务与对账" title="财务结算" description="已结算金额、待结算订单及佣金明细将在这里展示。" icon="¥" action="查看结算明细" />}
    </main>
    {showProductForm && <ProductDialog onClose={() => setShowProductForm(false)} onSubmit={createProduct} />}{showStockForm && <StockDialog onClose={() => setShowStockForm(false)} onSubmit={adjustStock} />}<div id="toast" className={toast ? 'visible' : ''}>{toast}</div>
  </div>;
}

function Overview({ products, orders, onNavigate, onNewProduct, onShip, onStock, notify }: { products: Product[]; orders: Order[]; onNavigate: (view: View) => void; onNewProduct: () => void; onShip: (id: string) => void; onStock: () => void; notify: (message: string) => void }) { const lowStock = products.filter((product) => product.stock < 21); const pending = orders.filter((order) => order.status === '待发货'); return <section className="content"><div className="page-heading"><div><p className="eyebrow">2026 年 8 月 18 日，星期二</p><h1>经营总览</h1><p className="muted">店铺经营数据每小时更新</p></div><div className="heading-actions"><button className="button secondary" onClick={() => notify('经营报表已开始生成，将发送至账户邮箱。')}>⇩ 下载报表</button><button className="button primary" onClick={onNewProduct}>＋ 新建商品</button></div></div><div className="notice"><span className="notice-icon">i</span><p><strong>库存提醒</strong><span>有 {lowStock.length} 个商品库存低于预警值，建议及时补货。</span></p><button className="link-button" onClick={() => onNavigate('inventory')}>查看库存</button></div><Metrics /><section className="dashboard-grid"><Trend /><RoutePanel onNavigate={onNavigate} /></section><section className="dashboard-grid lower-grid"><article className="panel"><div className="panel-header"><div><h2>待处理订单</h2><p>请在 24 小时内完成发货</p></div><button className="link-button" onClick={() => onNavigate('orders')}>订单中心</button></div>{pending.slice(0, 3).map((order) => <div className="order-preview" key={order.id}><div><span className="order-id">{order.id}</span><strong>{order.product}</strong><small>{order.recipient} · {order.city}</small></div><b>{order.amount}</b><button className="table-action" onClick={() => onShip(order.id)}>发货</button></div>)}</article><article className="panel stock-panel"><div className="panel-header"><div><h2>库存预警</h2><p>低于安全库存</p></div><button className="link-button" onClick={onStock}>去补货</button></div>{lowStock.map((product) => <div className="stock-row" key={product.sku}><img src={product.image} alt={product.name} /><div><strong>{product.name}</strong><small>{product.sku}</small></div><b className="danger">仅剩 {product.stock} 件</b></div>)}</article></section></section>; }
function Metrics() { return <section className="metric-grid"><article className="metric-card"><p>今日成交额 <button className="info" title="已支付订单的商品实付金额">i</button></p><strong>¥12,680.00</strong><span className="up">↑ 18.6%</span><small>较昨日</small></article><article className="metric-card"><p>支付订单</p><strong>86</strong><span className="up">↑ 12.1%</span><small>较昨日</small></article><article className="metric-card"><p>访客数</p><strong>2,438</strong><span className="up">↑ 8.4%</span><small>较昨日</small></article><article className="metric-card"><p>转化率</p><strong>3.53%</strong><span className="down">↓ 0.3%</span><small>较昨日</small></article></section>; }
function Trend() { return <article className="panel trend-panel"><div className="panel-header"><div><h2>成交趋势</h2><p>近 7 天</p></div><div className="legend"><span><i className="line-dot green" />成交额</span><span><i className="line-dot orange" />订单数</span></div></div><div className="chart"><div className="y-axis"><span>¥16k</span><span>¥12k</span><span>¥8k</span><span>¥4k</span><span>¥0</span></div><div className="plot">{[1, 2, 3, 4, 5].map((item) => <div className="grid-line" key={item} />)}<div className="chart-line">{[40, 55, 48, 68, 59, 80, 73].map((height, index) => <i className={index === 6 ? 'current' : ''} style={{ height: `${height}%` }} key={height} />)}</div><div className="chart-labels">{['12 日', '13 日', '14 日', '15 日', '16 日', '17 日', '18 日'].map((label) => <span key={label}>{label}</span>)}</div></div></div></article>; }
function RoutePanel({ onNavigate }: { onNavigate: (view: View) => void }) { const routes = [['teal', '周末轻徒步入门', '西山 5 公里路线', '¥2,840', '12 单'], ['orange', '城市骑行第一课', '城市骑行路线', '¥1,960', '8 单'], ['blue', '夏日露营清单', '两天一夜路线', '¥1,280', '5 单']]; return <article className="panel route-panel"><div className="panel-header"><div><h2>路线商品表现</h2><p>来自关联路线的成交</p></div><button className="link-button" onClick={() => onNavigate('offers')}>查看全部</button></div><div className="route-list">{routes.map(([color, title, description, amount, count]) => <div className="route-row" key={title}><span className={`route-icon ${color}`}>⌁</span><div><strong>{title}</strong><small>{description}</small></div><b>{amount}</b><span className="tag good">{count}</span></div>)}</div></article>; }
function Products({ products, search, status, onSearch, onStatus, onNew }: { products: Product[]; search: string; status: string; onSearch: (value: string) => void; onStatus: (value: string) => void; onNew: () => void }) { return <section className="content"><div className="page-heading"><div><p className="eyebrow">商品与 SKU</p><h1>商品管理</h1><p className="muted">管理店铺中上架、待发布和已下架的商品</p></div><button className="button primary" onClick={onNew}>＋ 新建商品</button></div><div className="panel table-panel"><div className="table-tools"><label className="search"><span>⌕</span><input value={search} onChange={(event) => onSearch(event.target.value)} placeholder="搜索商品名称或 SKU" /></label><select value={status} onChange={(event) => onStatus(event.target.value)}><option value="all">全部状态</option><option value="selling">销售中</option><option value="draft">待发布</option></select><button className="button secondary">筛选</button></div><div className="responsive-table"><table><thead><tr><th>商品</th><th>售价</th><th>库存</th><th>销量</th><th>状态</th><th /></tr></thead><tbody>{products.map((product) => <tr key={product.sku}><td><div className="product-cell"><img src={product.image} alt="" /><span><strong>{product.name}</strong><small>{product.sku}</small></span></div></td><td>{product.price}</td><td>{product.stock}</td><td>{product.sales}</td><td><span className={`status ${product.status === '销售中' ? 'success' : 'neutral'}`}>{product.status}</span></td><td><button className="icon-button more" title="更多操作">⋯</button></td></tr>)}</tbody></table></div></div></section>; }
function Orders({ orders, filter, onFilter, onShip }: { orders: Order[]; filter: string; onFilter: (filter: string) => void; onShip: (id: string) => void }) { const tabs = ['all', '待发货', '运输中', '已完成']; return <section className="content"><div className="page-heading"><div><p className="eyebrow">订单履约</p><h1>订单中心</h1><p className="muted">支付、发货和售后状态在此统一处理</p></div><button className="button secondary">⇩ 导出订单</button></div><div className="panel table-panel"><div className="table-tools"><div className="segmented">{tabs.map((tab) => <button className={filter === tab ? 'selected' : ''} onClick={() => onFilter(tab)} key={tab}>{tab === 'all' ? '全部' : tab}</button>)}</div><label className="search"><span>⌕</span><input placeholder="订单号、收件人或商品" /></label></div><div className="responsive-table"><table><thead><tr><th>订单号</th><th>商品</th><th>收件人</th><th>金额</th><th>状态</th><th>操作</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td>{order.id}<small>{order.date}</small></td><td>{order.product}</td><td>{order.recipient}<small>{order.city}</small></td><td>{order.amount}</td><td><span className={`status ${order.status === '待发货' ? 'warning' : order.status === '运输中' ? 'info-status' : 'success'}`}>{order.status}</span></td><td><button className="table-action" disabled={order.status !== '待发货'} onClick={() => onShip(order.id)}>{order.status === '待发货' ? '发货' : order.status === '运输中' ? '查看物流' : '订单详情'}</button></td></tr>)}</tbody></table></div></div></section>; }
function Inventory({ products, onAdjust }: { products: Product[]; onAdjust: () => void }) { return <section className="content"><div className="page-heading"><div><p className="eyebrow">仓储管理</p><h1>库存管理</h1><p className="muted">可用库存由库存服务统一维护，订单预占会自动扣减可售量</p></div><button className="button primary" onClick={onAdjust}>＋ 库存调整</button></div><div className="panel table-panel"><div className="table-tools"><label className="search"><span>⌕</span><input placeholder="搜索商品或 SKU" /></label><select><option>全部仓库</option><option>北京中心仓</option></select></div><div className="responsive-table"><table><thead><tr><th>商品 / SKU</th><th>可售库存</th><th>预占库存</th><th>安全库存</th><th>状态</th><th /></tr></thead><tbody>{products.slice(0, 3).map((product, index) => <tr key={product.sku}><td><strong>{product.name}</strong><small>{product.sku} · 北京中心仓</small></td><td className="stock-number">{product.stock}</td><td>{index === 0 ? 2 : index === 1 ? 4 : 1}</td><td>{index === 2 ? 20 : index === 1 ? 30 : 20}</td><td><span className={`status ${product.stock < 21 ? 'danger-status' : 'success'}`}>{product.stock < 21 ? '需补货' : '充足'}</span></td><td><button className="table-action" onClick={onAdjust}>调整</button></td></tr>)}</tbody></table></div></div></section>; }
function Placeholder({ eyebrow, title, description, icon, action }: { eyebrow: string; title: string; description: string; icon: string; action: string }) { return <section className="content placeholder-view"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted">{description}</p><div className="panel empty-state"><span>{icon}</span><h2>{title}正在建设</h2><p>当前原型展示核心经营流程，数据接口接入后可在此完成完整管理。</p><button className="button secondary">{action}</button></div></section>; }
function ProductDialog({ onClose, onSubmit }: { onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="modal-backdrop"><form className="modal" onSubmit={onSubmit}><div className="dialog-header"><div><p className="eyebrow">商品信息</p><h2>新建商品</h2></div><button type="button" className="icon-button" onClick={onClose} title="关闭">×</button></div><label>商品名称<input name="name" required placeholder="例如：轻量徒步背包 20L" /></label><div className="form-grid"><label>售价<input name="price" required type="number" min="0" step="0.01" placeholder="0.00" /></label><label>初始库存<input name="stock" required type="number" min="0" placeholder="0" /></label></div><label>商品描述<textarea placeholder="描述商品特点和适用场景" /></label><div className="dialog-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button className="button primary">创建商品</button></div></form></div>; }
function StockDialog({ onClose, onSubmit }: { onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="modal-backdrop"><form className="modal" onSubmit={onSubmit}><div className="dialog-header"><div><p className="eyebrow">库存调整</p><h2>调整可售库存</h2></div><button type="button" className="icon-button" onClick={onClose} title="关闭">×</button></div><label>调整数量<input name="quantity" required type="number" min="1" defaultValue="10" /></label><label>调整原因<select><option>采购入库</option><option>盘点修正</option><option>其他</option></select></label><div className="dialog-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button className="button primary">确认调整</button></div></form></div>; }

createRoot(document.querySelector('#root')!).render(<App />);
