[package]
name = "bookway-search-main"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bookway-search-main-api.workspace = true
async-trait.workspace = true
axum.workspace = true
bookway-api.workspace = true
bookway-bbs-link-api.workspace = true
bookway-bbs-search-api.workspace = true
bookway-data.workspace = true
bookway-runtime.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tower-http.workspace = true
tonic.workspace = true
tonic-health.workspace = true
prost.workspace = true
uuid.workspace = true

[lints]
workspace = true
