[package]
name = "bookway-entry-publication-dispatcher"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bookway-bbs-link-api.workspace = true
bookway-growth-api.workspace = true
bookway-data.workspace = true
bookway-runtime.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true
