[package]
name = "bookway-recommend-recall"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bookway-recommend-recall-api.workspace = true
axum.workspace = true
bookway-api.workspace = true
bookway-bbs-link-api.workspace = true
bookway-runtime.workspace = true
prost.workspace = true
futures.workspace = true
reqwest.workspace = true
tonic.workspace = true
tonic-health.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tracing.workspace = true
tower-http.workspace = true

[dev-dependencies]
tokio-stream.workspace = true


[lints]
workspace = true
