// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderItemRequest {
    #[prost(string, tag = "1")]
    pub sku_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub quantity: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub idempotency_key: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub items: ::prost::alloc::vec::Vec<OrderItemRequest>,
    /// Orders originate from an offer shown at a route action node; direct SKU
    /// checkout is intentionally not part of the commerce model.
    #[prost(string, tag = "4")]
    pub node_offer_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderLine {
    #[prost(string, tag = "1")]
    pub sku_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub product_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub title: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub quantity: u32,
    #[prost(int64, tag = "5")]
    pub unit_price_cents: i64,
    #[prost(string, tag = "6")]
    pub currency: ::prost::alloc::string::String,
    #[prost(int64, tag = "7")]
    pub line_total_cents: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Order {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(enumeration = "MallOrderStatus", tag = "3")]
    pub status: i32,
    #[prost(string, tag = "4")]
    pub currency: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub total_cents: i64,
    #[prost(message, repeated, tag = "6")]
    pub items: ::prost::alloc::vec::Vec<OrderLine>,
    #[prost(string, optional, tag = "7")]
    pub payment_reference: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "8")]
    pub expires_at: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub updated_at: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub node_offer_id: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub affiliate_creator_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "13")]
    pub commission_cents: i64,
    /// Immutable merchant snapshot from the contextual NodeOffer.
    #[prost(string, tag = "14")]
    pub merchant_id: ::prost::alloc::string::String,
    #[prost(enumeration = "FulfillmentStatus", tag = "15")]
    pub fulfillment_status: i32,
    #[prost(string, tag = "16")]
    pub tracking_number: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderListResponse {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<Order>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ExpirePendingResponse {
    #[prost(uint32, tag = "1")]
    pub scanned: u32,
    #[prost(uint32, tag = "2")]
    pub expired: u32,
    #[prost(uint32, tag = "3")]
    pub failed: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PayRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub payment_reference: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BatchRequest {
    #[prost(uint32, tag = "1")]
    pub limit: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MerchantOrderRequest {
    #[prost(string, tag = "1")]
    pub merchant_id: ::prost::alloc::string::String,
    #[prost(enumeration = "MallOrderStatus", optional, tag = "2")]
    pub status: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "3")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "4")]
    pub limit: ::core::option::Option<u32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MerchantOrderListResponse {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<Order>,
    #[prost(string, optional, tag = "2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateFulfillmentRequest {
    #[prost(string, tag = "1")]
    pub merchant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(enumeration = "FulfillmentStatus", tag = "3")]
    pub status: i32,
    #[prost(string, tag = "4")]
    pub tracking_number: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AffiliateSettlement {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub merchant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub creator_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub amount_cents: i64,
    #[prost(enumeration = "AffiliateSettlementStatus", tag = "6")]
    pub status: i32,
    #[prost(string, tag = "7")]
    pub eligible_at: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "8")]
    pub settled_at: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "9")]
    pub created_at: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AffiliateSettlementRequest {
    #[prost(string, tag = "1")]
    pub merchant_id: ::prost::alloc::string::String,
    #[prost(enumeration = "AffiliateSettlementStatus", optional, tag = "2")]
    pub status: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "3")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "4")]
    pub limit: ::core::option::Option<u32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AffiliateSettlementListResponse {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<AffiliateSettlement>,
    #[prost(string, optional, tag = "2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SettleAffiliateRequest {
    #[prost(string, tag = "1")]
    pub merchant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub settlement_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MallOrderStatus {
    PendingPayment = 0,
    Paid = 1,
    Cancelled = 2,
    Expired = 3,
    PaymentProcessing = 4,
}
impl MallOrderStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::PendingPayment => "MALL_ORDER_STATUS_PENDING_PAYMENT",
            Self::Paid => "MALL_ORDER_STATUS_PAID",
            Self::Cancelled => "MALL_ORDER_STATUS_CANCELLED",
            Self::Expired => "MALL_ORDER_STATUS_EXPIRED",
            Self::PaymentProcessing => "MALL_ORDER_STATUS_PAYMENT_PROCESSING",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MALL_ORDER_STATUS_PENDING_PAYMENT" => Some(Self::PendingPayment),
            "MALL_ORDER_STATUS_PAID" => Some(Self::Paid),
            "MALL_ORDER_STATUS_CANCELLED" => Some(Self::Cancelled),
            "MALL_ORDER_STATUS_EXPIRED" => Some(Self::Expired),
            "MALL_ORDER_STATUS_PAYMENT_PROCESSING" => Some(Self::PaymentProcessing),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FulfillmentStatus {
    Pending = 0,
    Processing = 1,
    Shipped = 2,
    Delivered = 3,
    Cancelled = 4,
}
impl FulfillmentStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Pending => "FULFILLMENT_STATUS_PENDING",
            Self::Processing => "FULFILLMENT_STATUS_PROCESSING",
            Self::Shipped => "FULFILLMENT_STATUS_SHIPPED",
            Self::Delivered => "FULFILLMENT_STATUS_DELIVERED",
            Self::Cancelled => "FULFILLMENT_STATUS_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FULFILLMENT_STATUS_PENDING" => Some(Self::Pending),
            "FULFILLMENT_STATUS_PROCESSING" => Some(Self::Processing),
            "FULFILLMENT_STATUS_SHIPPED" => Some(Self::Shipped),
            "FULFILLMENT_STATUS_DELIVERED" => Some(Self::Delivered),
            "FULFILLMENT_STATUS_CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AffiliateSettlementStatus {
    Pending = 0,
    Eligible = 1,
    Settled = 2,
    Reversed = 3,
}
impl AffiliateSettlementStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Pending => "AFFILIATE_SETTLEMENT_STATUS_PENDING",
            Self::Eligible => "AFFILIATE_SETTLEMENT_STATUS_ELIGIBLE",
            Self::Settled => "AFFILIATE_SETTLEMENT_STATUS_SETTLED",
            Self::Reversed => "AFFILIATE_SETTLEMENT_STATUS_REVERSED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AFFILIATE_SETTLEMENT_STATUS_PENDING" => Some(Self::Pending),
            "AFFILIATE_SETTLEMENT_STATUS_ELIGIBLE" => Some(Self::Eligible),
            "AFFILIATE_SETTLEMENT_STATUS_SETTLED" => Some(Self::Settled),
            "AFFILIATE_SETTLEMENT_STATUS_REVERSED" => Some(Self::Reversed),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod mall_order_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct MallOrderClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MallOrderClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MallOrderClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MallOrderClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MallOrderClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn create(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateRequest>,
        ) -> std::result::Result<tonic::Response<super::Order>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.mall.order.MallOrder/Create",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("bookway.mall.order.MallOrder", "Create"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list(
            &mut self,
            request: impl tonic::IntoRequest<super::UserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OrderListResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.mall.order.MallOrder/List",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("bookway.mall.order.MallOrder", "List"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get(
            &mut self,
            request: impl tonic::IntoRequest<super::OrderRequest>,
        ) -> std::result::Result<tonic::Response<super::Order>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.mall.order.MallOrder/Get",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("bookway.mall.order.MallOrder", "Get"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn pay(
            &mut self,
            request: impl tonic::IntoRequest<super::PayRequest>,
        ) -> std::result::Result<tonic::Response<super::Order>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.mall.order.MallOrder/Pay",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("bookway.mall.order.MallOrder", "Pay"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn cancel(
            &mut self,
            request: impl tonic::IntoRequest<super::OrderRequest>,
        ) -> std::result::Result<tonic::Response<super::Order>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.mall.order.MallOrder/Cancel",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("bookway.mall.order.MallOrder", "Cancel"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn expire_pending(
            &mut self,
            request: impl tonic::IntoRequest<super::BatchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExpirePendingResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.mall.order.MallOrder/ExpirePending",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("bookway.mall.order.MallOrder", "ExpirePending"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn merchant_orders(
            &mut self,
            request: impl tonic::IntoRequest<super::MerchantOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MerchantOrderListResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.mall.order.MallOrder/MerchantOrders",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("bookway.mall.order.MallOrder", "MerchantOrders"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_fulfillment(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateFulfillmentRequest>,
        ) -> std::result::Result<tonic::Response<super::Order>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.mall.order.MallOrder/UpdateFulfillment",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("bookway.mall.order.MallOrder", "UpdateFulfillment"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn affiliate_settlements(
            &mut self,
            request: impl tonic::IntoRequest<super::AffiliateSettlementRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AffiliateSettlementListResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.mall.order.MallOrder/AffiliateSettlements",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "bookway.mall.order.MallOrder",
                        "AffiliateSettlements",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn settle_affiliate(
            &mut self,
            request: impl tonic::IntoRequest<super::SettleAffiliateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AffiliateSettlement>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bookway.mall.order.MallOrder/SettleAffiliate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("bookway.mall.order.MallOrder", "SettleAffiliate"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod mall_order_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MallOrderServer.
    #[async_trait]
    pub trait MallOrder: std::marker::Send + std::marker::Sync + 'static {
        async fn create(
            &self,
            request: tonic::Request<super::CreateRequest>,
        ) -> std::result::Result<tonic::Response<super::Order>, tonic::Status>;
        async fn list(
            &self,
            request: tonic::Request<super::UserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OrderListResponse>,
            tonic::Status,
        >;
        async fn get(
            &self,
            request: tonic::Request<super::OrderRequest>,
        ) -> std::result::Result<tonic::Response<super::Order>, tonic::Status>;
        async fn pay(
            &self,
            request: tonic::Request<super::PayRequest>,
        ) -> std::result::Result<tonic::Response<super::Order>, tonic::Status>;
        async fn cancel(
            &self,
            request: tonic::Request<super::OrderRequest>,
        ) -> std::result::Result<tonic::Response<super::Order>, tonic::Status>;
        async fn expire_pending(
            &self,
            request: tonic::Request<super::BatchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExpirePendingResponse>,
            tonic::Status,
        >;
        async fn merchant_orders(
            &self,
            request: tonic::Request<super::MerchantOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MerchantOrderListResponse>,
            tonic::Status,
        >;
        async fn update_fulfillment(
            &self,
            request: tonic::Request<super::UpdateFulfillmentRequest>,
        ) -> std::result::Result<tonic::Response<super::Order>, tonic::Status>;
        async fn affiliate_settlements(
            &self,
            request: tonic::Request<super::AffiliateSettlementRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AffiliateSettlementListResponse>,
            tonic::Status,
        >;
        async fn settle_affiliate(
            &self,
            request: tonic::Request<super::SettleAffiliateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AffiliateSettlement>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct MallOrderServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MallOrderServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MallOrderServer<T>
    where
        T: MallOrder,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/bookway.mall.order.MallOrder/Create" => {
                    #[allow(non_camel_case_types)]
                    struct CreateSvc<T: MallOrder>(pub Arc<T>);
                    impl<T: MallOrder> tonic::server::UnaryService<super::CreateRequest>
                    for CreateSvc<T> {
                        type Response = super::Order;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MallOrder>::create(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.mall.order.MallOrder/List" => {
                    #[allow(non_camel_case_types)]
                    struct ListSvc<T: MallOrder>(pub Arc<T>);
                    impl<T: MallOrder> tonic::server::UnaryService<super::UserRequest>
                    for ListSvc<T> {
                        type Response = super::OrderListResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UserRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MallOrder>::list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.mall.order.MallOrder/Get" => {
                    #[allow(non_camel_case_types)]
                    struct GetSvc<T: MallOrder>(pub Arc<T>);
                    impl<T: MallOrder> tonic::server::UnaryService<super::OrderRequest>
                    for GetSvc<T> {
                        type Response = super::Order;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::OrderRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MallOrder>::get(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.mall.order.MallOrder/Pay" => {
                    #[allow(non_camel_case_types)]
                    struct PaySvc<T: MallOrder>(pub Arc<T>);
                    impl<T: MallOrder> tonic::server::UnaryService<super::PayRequest>
                    for PaySvc<T> {
                        type Response = super::Order;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PayRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MallOrder>::pay(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PaySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.mall.order.MallOrder/Cancel" => {
                    #[allow(non_camel_case_types)]
                    struct CancelSvc<T: MallOrder>(pub Arc<T>);
                    impl<T: MallOrder> tonic::server::UnaryService<super::OrderRequest>
                    for CancelSvc<T> {
                        type Response = super::Order;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::OrderRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MallOrder>::cancel(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CancelSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.mall.order.MallOrder/ExpirePending" => {
                    #[allow(non_camel_case_types)]
                    struct ExpirePendingSvc<T: MallOrder>(pub Arc<T>);
                    impl<T: MallOrder> tonic::server::UnaryService<super::BatchRequest>
                    for ExpirePendingSvc<T> {
                        type Response = super::ExpirePendingResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BatchRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MallOrder>::expire_pending(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExpirePendingSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.mall.order.MallOrder/MerchantOrders" => {
                    #[allow(non_camel_case_types)]
                    struct MerchantOrdersSvc<T: MallOrder>(pub Arc<T>);
                    impl<
                        T: MallOrder,
                    > tonic::server::UnaryService<super::MerchantOrderRequest>
                    for MerchantOrdersSvc<T> {
                        type Response = super::MerchantOrderListResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MerchantOrderRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MallOrder>::merchant_orders(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MerchantOrdersSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.mall.order.MallOrder/UpdateFulfillment" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateFulfillmentSvc<T: MallOrder>(pub Arc<T>);
                    impl<
                        T: MallOrder,
                    > tonic::server::UnaryService<super::UpdateFulfillmentRequest>
                    for UpdateFulfillmentSvc<T> {
                        type Response = super::Order;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateFulfillmentRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MallOrder>::update_fulfillment(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateFulfillmentSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.mall.order.MallOrder/AffiliateSettlements" => {
                    #[allow(non_camel_case_types)]
                    struct AffiliateSettlementsSvc<T: MallOrder>(pub Arc<T>);
                    impl<
                        T: MallOrder,
                    > tonic::server::UnaryService<super::AffiliateSettlementRequest>
                    for AffiliateSettlementsSvc<T> {
                        type Response = super::AffiliateSettlementListResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AffiliateSettlementRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MallOrder>::affiliate_settlements(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AffiliateSettlementsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bookway.mall.order.MallOrder/SettleAffiliate" => {
                    #[allow(non_camel_case_types)]
                    struct SettleAffiliateSvc<T: MallOrder>(pub Arc<T>);
                    impl<
                        T: MallOrder,
                    > tonic::server::UnaryService<super::SettleAffiliateRequest>
                    for SettleAffiliateSvc<T> {
                        type Response = super::AffiliateSettlement;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SettleAffiliateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MallOrder>::settle_affiliate(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SettleAffiliateSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for MallOrderServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "bookway.mall.order.MallOrder";
    impl<T> tonic::server::NamedService for MallOrderServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
